CREATE DATABASE IF NOT EXISTS shambapoint;
USE shambapoint;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(255) UNIQUE,
    password_hash VARCHAR(512) NOT NULL,
    role ENUM('Farmer', 'Buyer', 'Logistics', 'Admin') NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- If upgrading an existing install that lacks the email column, run this once:
-- ALTER TABLE users ADD COLUMN email VARCHAR(255) UNIQUE AFTER phone;

CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    farmer_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    quantity VARCHAR(50) NOT NULL,
    status ENUM('Available', 'Sold Out') DEFAULT 'Available',
    image_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (farmer_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    buyer_id INT NOT NULL,
    product_id INT NOT NULL,
    total_amount DECIMAL(10,2) NOT NULL,
    payment_status ENUM('Pending', 'Paid', 'Failed') DEFAULT 'Pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (buyer_id) REFERENCES users(id),
    FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS deliveries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT NOT NULL,
    driver_id INT,
    status ENUM('Pending', 'Picked Up', 'In Transit', 'Delivered') DEFAULT 'Pending',
    tracking_details TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (driver_id) REFERENCES users(id)
);

-- Create the dedicated app user (if it doesn't exist)
CREATE USER IF NOT EXISTS 'shambapoint_app'@'127.0.0.1' IDENTIFIED BY 'shamba_secure_pass_123!';
GRANT SELECT, INSERT, UPDATE, DELETE ON shambapoint.* TO 'shambapoint_app'@'127.0.0.1';
FLUSH PRIVILEGES;

-- ── BOOTSTRAP ADMIN ──────────────────────────────────────────────────────────
-- One-time bootstrap: creates the first Admin account.
-- Password hash below is generated by app.py's hash_password() function using
-- the password "BootstrapAdmin@123" — change it immediately after first login.
--
-- To generate a fresh hash, run in Python:
--   import hashlib, os
--   salt = os.urandom(16)
--   dk = hashlib.pbkdf2_hmac('sha256', b'YourNewPassword', salt, 100000)
--   print(salt.hex() + ':' + dk.hex())
--
-- Then replace the password_hash value below:
--
-- INSERT INTO users (name, phone, email, password_hash, role)
-- VALUES ('Bootstrap Admin', '+254700000000', 'admin@shambapoint.co.ke',
--         '<paste-your-hash-here>', 'Admin')
-- ON DUPLICATE KEY UPDATE id=id;
